packages:
  - "apps/*"
  - "packages/*"
  - "packages/*/*"
  - "packages/*/*/*"

allowBuilds:
  msw: false
  sharp: false
  unrs-resolver: false

ignoredBuiltDependencies:
  - msw
  - sharp
  - unrs-resolver
